# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b0c3e99d920aa77a058a1c35fc00c2ec9c30f90dd550fb22abe6e8c8827aec96ee8bf127ba6a56d4c40cb463eda4b496b11b4d83c594f7e55f411f3a7e738ca

test:
  secret_key_base: 2b1f3913a9b107189258b9d3eeeb5e6360b0220a11c28e2d609e085a12f518d3b6e418ce4e0cb3f273c23bc8c74a75ecd78924ca309864282d8bd5c727466efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
